### ISSUE TITLE
Change the Result module in morphir.sdk to use multiple argument lists for currying

### ISSUE THREAD

**Issue by DamianReeves** [Morgan-Stanley/morphir-jvm#30]
Currently the [Result](https://github.com/Morgan-Stanley/morphir-jvm/blob/master/morphir/sdk/core/src/org/morphir/sdk/Result.scala) type uses explicit currying by returning a chain of function objects. This appears to provide a less than ideal experience with type inference. Change to using multiple argument lists instead (The `List` module already uses the target approach).

For example, instead of:

```scala
  def map[E, A, A1](fn: A => A1): Result[E, A] => Result[E, A1] =
    (result: Result[E, A]) => result.map(fn)
```

the map function should be defined as:

```scala
  def map[E, A, A1](fn: A => A1)(result:Result[E,A]): Result[E, A1] = 
     result.map(fn)
```

**Comment by stephengoldbaum** [comment]
Updated Result and related tests
